user_login:
    path:     /login
    defaults: { _controller: GeoGuesserBundle:Security:login }

user_login_check:
    path:     /login_check
    defaults: { _controller: GeoGuesserBundle:Security:check }

user_logout:
    path:     /logout
    defaults: { _controller: GeoGuesserBundle:Security:logout }

#homepage
ged_homepage:
    path:     /
    defaults: { _controller: GeoGuesserBundle:Default:index }