<?php

namespace GeoGuesserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * inventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inventoryRepository extends EntityRepository
{
}
