<?php

namespace GeoGuesserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
	public function findOneRandom()
    {
        $em = $this->getEntityManager();
        $max = $em->createQuery('
            SELECT MAX(q.id) FROM GeoGuesserBundle:Map q
            ')
            ->getSingleScalarResult();
        return $em->createQuery('
            SELECT q FROM GeoGuesserBundle:Map q
            WHERE q.id >= :rand
            ORDER BY q.id ASC
            ')
            ->setParameter('rand',rand(0,$max))
            ->setMaxResults(1)
            ->getSingleResult();
    }
}
